### ISSUE TITLE
Request to have a manual to install alongside a fresh archlinux

### ISSUE THREAD

**Issue by mh-firouzjah** [Barbaross93/Nebula#10]
hi there, first of all thank you. that was a great job!
I'm new to linux and I started with arch base distros like Manjaro and Arcolinux, but soon I went for Arch and after reading the wiki-Arch  and some posts about installation and partitioning and so... I wrote a manual for myself and anyone like me, in [here](https://gist.github.com/mh-firouzjah/baa343cd79d4c336ef9820f4ebd34758), but it's not a complete one. so I'm here to ask you if it is possible to help me finish that article. thank you again.

**Comment by Barbarossa93** [comment]
Hey, glad you liked it! I'm pretty swamped with life at the moment, but at some point I can give my suggestions.

**Comment by mh-firouzjaah** [comment]
thank you for that. I will wait for your reply

**Comment by imskr** [comment]
@Barbarossa93 Can you please add steps of installation on fresh arch install?

**Comment by Barbaross93** [comment]
Sorry it took so long for me to get around to this! Looks like the link you provided is dead. Do you have it somewhere else?

**Comment by mh-firouzjah** [comment]
hi, there was a typo in the link thanks for your comment.(fixed)

**Comment by Barbaross93** [comment]
Honestly, it looks good! I think I might add a section at the top letting people know that they are free to use whatever options they prefer. Some links to documentation regarding specific options would be great e.g. when you went through creating the btrfs subvolumes have a link there or when you are adding groups for the user, a link to the relevant arch wiki page would be helpful. As it stands now, its definitely written for a very specific setup (YOUR setup ;)) so just letting folks be aware that there's more out there than what you have put together is a good thing to have on their radars.

**Comment by SakethKanchi** [comment]
Really cool rice. Requesting for installation on fresh arch install or EndeavourOS

**Comment by SakethKanchi** [comment]
Really cool rice. Requesting for installation on fresh arch install or EndeavourOS
