### ISSUE TITLE
circle-half-right not showing in panel

### ISSUE THREAD

**Issue by ryanwwhittaker** [Barbaross93/Nebula#14]
Hi,
I have both the Font-Awesome TTF and FiraCode Nerd Fonts installed on my Manjaro system.
All looking good except the circle-half-right on each widget is missing in the panel.
Interestingly the left half circles are fine and look good, so it is just the trailing ones that are missing.
Any ideas?
Great looking config by the way!
Thanks

**Comment by Barbaross93** [comment]
Strange, I'm not quite sure. Maybe you need to adjust their size? My setup is for a 4k monitor, so everything will likely need to be down scaled for most people's setups.
